cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path("", views.index, name="index")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('greetings/', include('greetings.urls')),
    path('students/', include('students.urls')),
    path('state/', include('state.urls')),
    path('employee/', include('employee.urls')),
    path('media/', include('media_app.urls')),
    path('cookie-session-app/', include('cookie_session_app.urls')),
    path('client-project-app/', include('client_project.urls')),
    path('bootstrap-practice-app/', include('bootstrap_practice_app.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('pet-store/', include('pet_store.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from . import views

app_name = 'students'
urlpatterns = [
    path('', views.StudentListView.as_view(), name='student_list'),
    path('add', views.StudentCreateView.as_view(), name='student_form'),
    path('update/<int:id>', views.update_details, name='student_update'),
    path('delete/<int:pk>', views.DeleteDetailsView.as_view(), name='student_delete')
]

students/models.py
from django.db import models

# Create your models here.


class Student(models.Model):
    student_name = models.CharField(max_length=150, blank=False, null=False)
    email = models.EmailField(unique=True, blank=False, null=False)
    age = models.IntegerField(blank=False, null=False)

    def __str__(self) -> str:
        return f'{self.student_name}'

students/forms.py
from django.forms import ModelForm
from .models import Student


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

students/views.py
from typing import Any
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from .forms import StudentForm
from .models import Student
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse_lazy
import json


class StudentCreateView(CreateView):
    template_name = 'students/form.html'
    form_class = StudentForm
    success_url = reverse_lazy('students:student_list')


class StudentListView(ListView):
    model = Student
    template_name = 'students/index.html'


@csrf_exempt
def update_details(request, id):
    if request.method == 'PATCH':
        data = json.loads(request.body)
        student1 = Student.objects.get(id=id)
        student1.student_name = data['student_name']
        student1.email = data['email']
        student1.age = int(data['age'])
        student1.save()
        return JsonResponse(data={'success': True})


class DeleteDetailsView(DeleteView):
    model = Student
    success_url = reverse_lazy('students:student_list')

students/templates/students/form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    students form
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'students/css/style.css' %}" >
{% endblock %}

{% block content %}
    <form method="post" action="{% url 'students:student_form' %}">
        {% csrf_token %}
        {{form.as_p}}
        {% if form.errors %}
            <p>Error!! Please try again.</p>
        {% endif %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

students/templates/students/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    student details
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'students/css/style.css' %}" >
{% endblock %}

{% block content %}
    <a class="btn btn-primary" href="{% url 'students:student_form' %}" >+ Add Student Details</a>
    <table>
        <thead>
            <th>Student ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Age</th>
            <th>Actions</th>
        </thead>
        <tbody>
            {% for student in student_list %}
                <tr>
                    <td>{{student.id}}</td>
                    <td><input id="text-{{student.id}}" type="text" value="{{student.student_name}}" class="form-control text-black student-input-{{student.id}}" disabled="true"></td>
                    <td><input id="email-{{student.id}}" type="email" value="{{student.email}}" class="form-control text-black student-input-{{student.id}}" disabled="true" ></td>
                    <td><input id="age-{{student.id}}" type="number" value="{{student.age}}" class="form-control text-black student-input-{{student.id}}" disabled="true" ></td>
                    <td>
                        <button id="edit-btn-{{student.id}}" class="edit-btn btn btn-outline-success">Edit</button>
                        <button hidden id="update-btn-{{student.id}}" class="update-btn btn btn-outline-warning">Update</button>
                        <a href="{% url 'students:student_delete' student.id %}" id="delete-btn-{{student.id}}" class="delete-btn btn btn-outline-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script>
        const editBtnList = document.querySelectorAll('.edit-btn')
        const updateBtnList = document.querySelectorAll('.update-btn')
        function editDetails(e) {
            let id = e.target.id.split('-')[2]
            let inputs = document.querySelectorAll(`.student-input-${id}`)
            for(let i=0; i<inputs.length; i++){
                inputs[i].removeAttribute('disabled')
            }
            document.getElementById(`update-btn-${id}`).removeAttribute('hidden')
            e.target.setAttribute('hidden',true)
        }
        function updateDetails(e){
            let id = e.target.id.split('-')[2]
            let inputs = document.querySelectorAll(`.student-input-${id}`)
            fetch(`/students/update/${id}`,{
                method:'PATCH',
                headers:{
                    'Content-Type':'application/json',
                    'X-CSRFToken': '{% csrf_token %}'
                },
                body:JSON.stringify({
                    id,
                    'student_name':document.getElementById(`text-${id}`).value,
                    email : document.getElementById(`email-${id}`).value,
                    age: document.getElementById(`age-${id}`).value
                })
            }).then((d)=>{
                document.getElementById(`edit-btn-${id}`).removeAttribute('hidden')
                e.target.setAttribute('hidden',true)
                for(let i=0; i<inputs.length; i++){
                    inputs[i].setAttribute('disabled',true)
                }
            }).catch((e)=>{
                console.log(e)
            })
        }
        
        for(let i=0; i<editBtnList.length; i++){
                editBtnList[i].addEventListener('click',editDetails)
                updateBtnList[i].addEventListener('click',updateDetails)
        }
        
    </script>
{% endblock %}

students/templates/students/student_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    confirm delete
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm" class="btn btn-danger">
    </form>
{% endblock %}