cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path("", views.index, name="index")
]

client_project/urls.py
from django.urls import path
from . import views

app_name = 'client_project_app'
urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
    path("login", views.UserLoginView.as_view(), name='login'),
    path("logout", views.logout_view, name='logout'),
    path('clients', views.ClientListView.as_view(), name='client_list'),
    path('clients/add', views.ClientRegisterView.as_view(), name='create_client'),
    path('clients/<int:pk>', views.ClientDetailView.as_view(), name='client_details'),
    path('client/update/<int:pk>',
         views.ClientUpdateView.as_view(), name='update_client'),
    path('client/delete/<int:pk>',
         views.ClientDeleteView.as_view(), name='delete_client'),
    path('projects/add', views.ProjectCreateView.as_view(), name='create_project'),
    path('projects/<int:pk>', views.ProjectDetailView.as_view(),
         name='project_details')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('greetings/', include('greetings.urls')),
    path('students/', include('students.urls')),
    path('state/', include('state.urls')),
    path('employee/', include('employee.urls')),
    path('media/', include('media_app.urls')),
    path('cookie-session-app/', include('cookie_session_app.urls')),
    path('client-project-app/', include('client_project.urls')),
    path('bootstrap-practice-app/', include('bootstrap_practice_app.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('pet-store/', include('pet_store.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client_project/models.py
from django.db import models
from django.contrib.auth.models import User


class Client(models.Model):
    name = models.CharField(max_length=150, blank=False, null=False)
    email = models.EmailField(unique=True)
    address = models.CharField(max_length=255, blank=False, null=False)

    def __str__(self) -> str:
        return f'{self.name}\n{self.email}\n{self.address}'


class Project(models.Model):
    name = models.CharField(max_length=150, blank=False, null=False)
    description = models.TextField(blank=False, null=False)
    client = models.ForeignKey(
        Client, on_delete=models.CASCADE, null=False, blank=False, related_name='projects')
    users = models.ManyToManyField(User)

client_project/forms.py
from django.forms import ModelForm, Form
from django import forms
from .models import Client, Project, User


class ClientForm(ModelForm):
    class Meta:
        model = Client
        fields = '__all__'


class ProjectForm(ModelForm):
    users = forms.ModelMultipleChoiceField(
        queryset=User.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Project
        fields = '__all__'

client_project/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from .forms import ClientForm, ProjectForm
from .models import Client, Project
from django.contrib.auth.models import User


class UserLoginView(LoginView):
    template_name = 'client_project/login.html'
    next_page = reverse_lazy('client_project_app:index')


class IndexView(LoginRequiredMixin, ListView):
    model = Project
    template_name = 'client_project/index.html'
    login_url = reverse_lazy('client_project_app:login')

    def get_queryset(self):
        return self.request.user.project_set.all()


class ClientRegisterView(LoginRequiredMixin, CreateView):
    form_class = ClientForm
    template_name = 'client_project/client_register_form.html'
    login_url = reverse_lazy('client_project_app:login')

    def get_success_url(self) -> str:
        return reverse_lazy('client_project_app:client_details', args=[self.object.id])


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name = 'client_project/client_list.html'
    login_url = reverse_lazy('client_project_app:login')


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client
    template_name = 'client_project/client_detail_page.html'
    login_url = reverse_lazy('client_project_app:login')


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'client_project/client_update_page.html'
    login_url = reverse_lazy('client_project_app:login')

    def get_success_url(self) -> str:
        return reverse_lazy('client_project_app:client_details', args=[self.object.id])


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('client_project_app:client_list')
    login_url = reverse_lazy('client_project_app:login')


class ProjectCreateView(LoginRequiredMixin, CreateView):
    form_class = ProjectForm
    template_name = 'client_project/project_create_page.html'
    login_url = reverse_lazy('client_project_app:login')
    success_url = reverse_lazy('client_project_app:index')


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = 'client_project/project_detail_page.html'
    login_url = reverse_lazy('client_project_app:login')


def logout_view(request):
    user = request.user
    if user.is_authenticated:
        logout(request)
        return HttpResponse('Logged out successfully!')
    return HttpResponseRedirect(reverse('client_project_app:login'))

client_project/templates/client_project/client_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    confirm delete
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm" class="btn btn-danger">
    </form>
{% endblock %}

client_project/templates/client_project/client_detail_page.html
{% extends 'base.html' %}

{% block title %}
    client {{client.name}}
{% endblock %}

{% block content %}
    <main class="h-100 min-vh-100">
        <div class="container bg-body-secondary h-100 min-vh-100 px-3">
            {% include 'client_project/includes/header.html' %}
            <div class="d-flex mt-4 justify-content-center">
                <div class="p-4 rounded-2 bg-white w-50">
                    <h3 class="mb-3">{{client.name}}</h3>
                    <p>{{client.email}}</p>
                    <p>{{client.address}}</p>
                    <div class="d-flex mt-3 column-gap-1">
                        <a href="{% url 'client_project_app:update_client' client.id %}" id="edit_btn" class="btn btn-outline-success">
                            <i class="fa-regular fa-pen-to-square"></i>
                        </a>
                        <a href="{% url 'client_project_app:delete_client' client.id %}" id="delete_btn" class="btn btn-outline-danger">
                            <i class="fa-solid fa-trash"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

client_project/templates/client_project/client_list.html
{% extends 'base.html' %}

{% block title %}
    client-list
{% endblock %}

{% block content %}
    <main class="h-100 min-vh-100">
        <div class="container bg-body-secondary h-100 min-vh-100 px-3">
            {% include 'client_project/includes/header.html' %}
            <div class="mt-4 d-flex column-gap-4">
                {% for client in client_list %}
                    <div class="p-4 rounded-2 bg-white">
                        <h3 class="mb-3"><a href="{% url 'client_project_app:client_details' client.id %}">{{client.name}}</a></h3>
                        <p>{{client.email}}</p>
                        <p>{{client.address}}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock %}

client_project/templates/client_project/client_register_form.html
{% extends 'base.html' %}

{% block title %}
    client-register
{% endblock %}

{% block content %}
    <main class="h-100 min-vh-100">
        <div class="container bg-body-secondary h-100 min-vh-100 px-3">
            {% include 'client_project/includes/header.html' %}
            <div class="d-flex mt-4 justify-content-center">
                <form method="post" action="{% url 'client_project_app:create_client' %}" class="d-flex flex-column row-gap-2 p-4 bg-white rounded-2">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="d-flex flex-column ">
                            {{field.label_tag}}
                            {{field}}
                        </div>
                    {% endfor %}
                    <button type="submit" class="mt-3 align-self-center btn btn-success">Register Client</button>
                </form>
            </div>
        </div>
    </main>
{% endblock %}

client_project/templates/client_project/client_update_page.html
{% extends 'base.html' %}

{% block title %}
    client update
{% endblock %}

{% block content %}
    <main class="h-100 min-vh-100">
        <div class="container bg-body-secondary h-100 min-vh-100 px-3">
            {% include 'client_project/includes/header.html' %}
            <div class="d-flex mt-4 justify-content-center">
                <form method="post" action="{% url 'client_project_app:update_client' client.id %}" class="d-flex flex-column row-gap-2 p-4 bg-white rounded-2">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="d-flex flex-column ">
                            {{field.label_tag}}
                            {{field}}
                        </div>
                    {% endfor %}
                    <button type="submit" class="mt-3 align-self-center btn btn-success">Update Client</button>
                </form>
            </div>
        </div>
    </main>
{% endblock %}

client_project/templates/client_project/index.html
{% extends 'base.html' %}

{% block title %}
    client-project
{% endblock %}

{% block content %}
    <main class="h-100 min-vh-100">
        <div class="container bg-body-secondary h-100 min-vh-100 px-3">
            {% include 'client_project/includes/header.html' %}
            <h2 class="mt-3 ms-2">Assigned Projects</h2>
            {% if project_list %}
            <div class="mt-4 d-flex column-gap-4">
                {% for project in project_list %}
                        <div class="p-4 rounded-2 bg-white">
                            <h3 class="mb-3"><a href="{% url 'client_project_app:project_details' project.id %}">{{project.name}}</a></h3>
                            <p>{{project.description}}</p>
                        </div>
                {% endfor %}
            </div>
            {% else %}
                <p class="ms-2" >No Project Assigned</p>
            {% endif %}
    </div>
        </div>
    </main>
{% endblock %}

client_project/templates/client_project/login.html
{% extends 'base.html' %}

{% block title %}
    login
{% endblock %}

{% block content %}
    <main class="">
        <div class="container">
            <div class="d-flex mt-4 justify-content-center">
                <form method="post" action="{% url 'client_project_app:login' %}" class="d-flex flex-column row-gap-2">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="d-flex flex-column ">
                            {{field.label_tag}}
                            {{field}}
                        </div>
                    {% endfor %}
                    <button type="submit" class="mt-3 align-self-center btn btn-primary">Log In</button>
                    {% if form.errors %}
                        <p class="text-danger fs-6">Wrong credentials!! Please try again.</p>
                    {% endif %}
                </form>
            </div>
        </div>
    </main>
{% endblock %}

client_project/templates/client_project/project_create_page.html
{% extends 'base.html' %}

{% block title %}
    create project
{% endblock %}

{% block content %}
    <main class="h-100 min-vh-100">
        <div class="container bg-body-secondary h-100 min-vh-100 px-3">
            {% include 'client_project/includes/header.html' %}
            <div class="d-flex mt-4 justify-content-center">
                <form method="post" action="{% url 'client_project_app:create_project' %}" class="d-flex flex-column row-gap-2 p-4 bg-white rounded-2">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="d-flex flex-column ">
                            {{field.label_tag}}
                            {{field}}
                        </div>
                    {% endfor %}
                    <button type="submit" class="mt-3 align-self-center btn btn-success">Create Project</button>
                </form>
            </div>
        </div>
    </main>
{% endblock %}

client_project/templates/client_project/project_detail_page.html
{% extends 'base.html' %}

{% block title %}
    project {{project.name}}
{% endblock %}

{% block content %}
    <main class="h-100 min-vh-100">
        <div class="container bg-body-secondary h-100 min-vh-100 px-3">
            {% include 'client_project/includes/header.html' %}
            <div class="d-flex mt-4 justify-content-center">
                <div class="p-4 rounded-2 bg-white w-25">
                    <h3 class="mb-3">{{project.name}}</h3>
                    <p>{{project.description}}</p>
                    <div >
                        <h5>Client:</h5>
                        <p>{{project.client.name}}</p>
                    </div>
                    <div>
                        <h5>Users:</h5>
                        {% for user in project.users.all %}
                            <p class="mb-0">{{user.username}}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}