cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path("", views.index, name="index")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('greetings/', include('greetings.urls')),
    path('students/', include('students.urls')),
    path('state/', include('state.urls')),
    path('employee/', include('employee.urls')),
    path('media/', include('media_app.urls')),
    path('cookie-session-app/', include('cookie_session_app.urls')),
    path('client-project-app/', include('client_project.urls')),
    path('bootstrap-practice-app/', include('bootstrap_practice_app.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('pet-store/', include('pet_store.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

state/urls.py
from django.urls import path
from . import views

app_name = "state"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>", views.StateDetailsView.as_view(), name="state_details"),
    path("add", views.StateCreateView.as_view(), name="state_add"),
    path("update/<int:pk>", views.StateDetailsUpdateView.as_view(),
         name="state_update"),
    path("delete/<int:pk>", views.StateDetailsDeleteView.as_view(), name='state_delete')
]

state/models.py
from django.db import models


class State(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False)
    capital = models.CharField(max_length=150, blank=False, null=False)
    language = models.CharField(max_length=100, blank=False, null=False)
    population = models.IntegerField(blank=False, null=False)

    def __str__(self) -> str:
        return f"""{self.name}\ncapital    : {self.capital}\nlanguage   : {self.language}\npopulation : {self.population}"""

state/forms.py
from django.forms import ModelForm
from .models import State


class StateDetailsForm(ModelForm):
    class Meta:
        model = State
        fields = '__all__'

state/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import State
from .forms import StateDetailsForm
from django.urls import reverse_lazy, reverse


class IndexView(ListView):
    model = State
    template_name = 'state/index.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        state_form = StateDetailsForm()
        context['state_form'] = state_form
        return context


class StateCreateView(CreateView):
    form_class = StateDetailsForm

    def get_success_url(self) -> str:
        return reverse('state:state_details', args=[self.object.id])


class StateDetailsView(DetailView):
    model = State
    template_name = 'state/state_details.html'


class StateDetailsUpdateView(UpdateView):
    model = State
    form_class = StateDetailsForm
    template_name = 'state/state_details_update.html'

    def get_success_url(self) -> str:
        return reverse('state:state_details', args=[self.object.id])


class StateDetailsDeleteView(DeleteView):
    model = State
    success_url = reverse_lazy('state:index')

state/templates/state/index.html
{% extends 'base.html' %}

{% block title %}
    state
{% endblock %}

{% block content %}
    <main class="d-flex flex-column align-items-center p-3 row-gap-3">
        <form method="post" action="{% url 'state:state_add' %}">
            {% csrf_token %}
            <table class="table table-bordered border-secondary">
                <tbody>
                    {% for field in state_form %}
                        <tr>
                            <th class="opacity-75">{{field.label_tag}}</th>
                            <td>    
                                {{field}}
                            </td>
                        </tr>                    
                    {% endfor %}
                    <tr>
                        <td colspan="2" class="text-center">
                            <button class="btn btn-primary mx-auto" type="submit">Add State</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
        <div class="d-flex column-gap-2">
            {% for state in state_list %}
                <a href="{% url 'state:state_details' state.id %}" class="btn btn-outline-secondary">{{state.name}}</a>
            {% endfor %}
        </div>
    </main>
{% endblock %}

state/templates/state/state_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    confirm delete
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm" class="btn btn-danger">
    </form>
{% endblock %}

state/templates/state/state_details.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}
    {{state.name}}
{% endblock %}

{% block content %}
    <main class="">
        <div class="d-flex align-items-center justify-content-center mt-5 ">
            <div class="w-50 py-5 px-4 rounded-2 shadow d-flex flex-column align-items-center row-gap-2">
                <h1 class="fw-semibold mb-4">{{state.name}}</h1>
                <div class="d-flex align-items-center column-gap-2">
                    <h2 class="fs-5 fw-bold opacity-75 mb-0">Capital :</h2>
                    <span class="state-detail fs-5 opacity-75 fw-medium" data-type="text" data-name="capital" >{{state.capital}}</span>
                </div>
                <div class="d-flex align-items-center column-gap-2">
                    <h2 class="fs-5 fw-bold opacity-75 mb-0">Language :</h2>
                    <span class="state-detail fs-5 opacity-75 fw-medium" data-type="text" data-name="language" >{{state.language}}</span>
                </div>
                <div class="d-flex align-items-center column-gap-2">
                    <h2 class="fs-5 fw-bold opacity-75 mb-0">Population :</h2>
                    <span class="state-detail fs-5 opacity-75 fw-medium" data-type="number" data-name="population" >{{state.population|intcomma}}</span>
                </div>
                <div class="d-flex align-self-end mt-3 column-gap-1">
                    <a href="{% url 'state:state_update' state.id %}" id="edit_btn" class="btn btn-outline-success">
                        <i class="fa-regular fa-pen-to-square"></i>
                    </a>
                    <a href="{% url 'state:state_delete' state.id %}" id="delete_btn" class="btn btn-outline-danger">
                        <i class="fa-solid fa-trash"></i>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

state/templates/state/state_details_update.html
{% extends 'base.html' %}

{% block title %}
    state
{% endblock %}

{% block content %}
    <main class="d-flex flex-column align-items-center p-3 row-gap-3">
        <form method="post" action="{% url 'state:state_update' state.id %}">
            {% csrf_token %}
            <table class="table table-bordered border-secondary">
                <tbody>
                    {% for field in form %}
                        <tr>
                            <th class="opacity-75">{{field.label_tag}}</th>
                            <td>    
                                {{field}}
                            </td>
                        </tr>                    
                    {% endfor %}
                    <tr>
                        <td colspan="2" class="text-center">
                            <button class="btn btn-primary mx-auto" type="submit">Update State</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </main>
{% endblock %}